version: '2.1'

services:
  api-tyba-restaurants:
    image: api-restaurants
    build:
      context: .
      dockerfile: DockerFile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links: 
      - redis:redis
  redis:
    image: 'redis:alpine'