FROM node:10.13-alpine
ENV NODE_ENV production
COPY ["package.json", "package-lock.json*", "ormconfig.json", "database.sqlite", "npm-shrinkwrap.json*", "opt/app/"]
RUN npm install --prefix /opt/app --production
COPY build/ /opt/app/build/
WORKDIR /opt/app
CMD npm start